// constants.dart

import 'package:car_maintanance/constants/constants_cust.dart';

List<String> brands = [
  ConstName.brand,
  'AstonMartin',
  'Audi',
  'BMW',
  'Bentley',
  'Chevrolet',
  'Ferrari',
  'Fiat',
  'Ford',
  'Honda',
  'Hyundai',
  'Jaguar',
  'Kia',
  'LandRover',
  'Lamborghini',
  'Lexus',
  'MahindraAndMahindra',
  'Maserati',
  'MercedesBenz',
  'Nissan',
  'Porsche',
  'Renault',
  'RollsRoyce',
  'Skoda',
  'Tata Motors',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'Other',
];
